import Providers from './Providers'
import Provides from './Providers'
import './globals.css'


export const metadata = {
  title: 'Suniti Portfolio',
  description: 'Generated by suniti',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body>
        <Providers>{children}</Providers>
     </body>
    </html>
  )
}

